<!DOCTYPE html>
<html lang="es">
<head>
	<title>BABYSELL</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximun-scale=1.0">
	<link rel="stylesheet" type="text/css" href="BIENVENIDA.css">
</head>
<body>
	<div id="contenedor">
		<div id="header">
			<div class="titulo">
				<h1 class="nombre">BABYSELL</h1>
				<h2 class="sudnombre">STORE</h2>
			</div>
		<div>
		<div id="nav"></div>
		<div id="contenido">
			<div id="section">
				<div class="boton">
					<button class="buscar">
							<a href="file:///C:/Users/manos/Desktop/PAGINA%20WEB/Pagina%20Principal.html" class="buscar">Inicio</a>
					</button>
				</div>
			</div>
		</div>
		<div id="footer"></div>
	</div>
</body>
</html>
